<?php
/**
 * Created by PhpStorm.
 * User: Tuan Long
 * Date: 10/29/2014
 * Time: 8:35 PM
 */

/**
 * class Worker_controller
*/
class Worker_controller extends Frontend_Controller{

    function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stub
        $this->load->module('template/template_controller');
    }

    /**
     * @param      $module
     * @param      $method
     * @param null $data
     */
    private function render($module, $method, $data = NULL)
    {
        $this->template_controller->demo_template($module, $method, $data);
    }

    public function index($data = NULL){
        $data['controller'] = 'worker_controller';
        $data['action'] = '';
        $data['module'] = 'worker';
        $this->render('worker','/index',$data);
    }

    public  function view_worker($data = NULL){
        $data['controller'] = 'worker_controller';
        $data['action'] = '';
        $data['module'] = 'worker';
        $this->render('worker','/worker',$data);
    }


}
