<?php
/**
 * Created by PhpStorm.
 * User: Tuan Long
 * Date: 10/28/2014
 * Time: 12:39 PM
 */

namespace super_classes;

class InkiuComment extends Comment{

    public function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stub
    }

    /**
     * @var
     */
    var $img_id;

    /**
     * @var
     */
    var $reviewer_id;

    /**
     * @var
     */
    var $status;

    /**
     * @return mixed
     */
    public function getImgId()
    {
        return $this->img_id;
    }

    /**
     * @param mixed $info
     */
    public function setImgId($info)
    {
        $this->img_id = $this->init_set($info, 'img_id');
    }

    /**
     * @return mixed
     */
    public function getReviewerId()
    {
        return $this->reviewer_id;
    }

    /**
     * @param mixed $info
     */
    public function setReviewerId($info)
    {
        $this->reviewer_id = $this->init_set($info, 'reviewer_id');
    }

    /**
     * @return mixed
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * @param mixed $info
     */
    public function setStatus($info)
    {
        $this->status = $this->init_set($info, 'status');
    }

    public function get_props()
    {
        $props = array(
            'id' => $this->id,
            'content' => $this->content,
            'time_commented' => $this->time_commented,
            'img_id' => $this->img_id,
            'reviewer_id' => $this->reviewer_id,
            'status' => $this->status
        );
        return $props;
    }


}