<?php
/**
 * Created by PhpStorm.
 * User: Tuan Long
 * Date: 10/1/2014
 * Time: 9:42 AM
 */
class Upload_controller extends Frontend_Controller{
    function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stub
        $this->load->module('template/template_controller');
    }


    //create view upload
    public function view_upload(){
        $data['controller'] = 'upload_controller';
        $data['action'] = 'upload';
        $data['module'] = 'order';

        $this->load->module('template/template_controller');
        $this->template_controller->demo_template('order', '/upload',$data);
    }

    //create view upload_mobile

    public function view_mobile_upload(){
        $data['controller'] = 'upload_controller';
        $data['action'] = 'mobile_upload';
        $data['module'] = 'order';

        $this->load->module('template/template_controller');
        $this->template_controller->demo_template('order', '/upload_mobile',$data);
    }

    //upload image file
    public function upload(){
        if(!empty($_FILES['files'])){
            $status = $this->save_files();
            if($status){
                echo 'File was saved !';
            }
        }else{
            echo 'Please choose your images !';
        }

   }

    //mobile upload images
    public function  mobile_upload(){
        if(!empty($_FILES['files'])){
            $status = $this->save_files();
            if($status){
                echo 'File was saved !';
            }
        }else{
            $this->view_mobile_upload();
        }
    }

    //function send file to irbs-fms
    private  function  save_files(){
        $status = '';
        foreach ($_FILES['files']['name'] as $key => $name) {
            if ($_FILES['files']['error'][$key] == 0) {
                $status = $this->call_fms_sender($key, $name);
            }
        }
        return $status;
    }
    private function call_fms_sender($key, $name)
    {
        $image = array(
            'image' => '@'
                .$_FILES['files']['tmp_name'][$key]
                .';filename='.$name
                .';type='.$_FILES['files']['type'][$key]
        );
        //$data = http_build_query($image, NULL, '&');
        $url ='http://localhost/irbs-fms/index.php/file/image_controller/call_fms_receiver';

        //initialise the curl request
        $request = curl_init();
        curl_setopt($request,CURLOPT_URL,$url);
        curl_setopt($request,CURLOPT_HEADER,true);
        curl_setopt($request,CURLOPT_HTTPHEADER,array("Content-Type:multipart/form-data"));
        curl_setopt($request,CURLOPT_USERAGENT,"Mozilla/5.0 (Windows; U; Windows NT 6.1; rv:2.2) Gecko/20110201");

        //send a file
        curl_setopt($request,CURLOPT_INFILESIZE,filesize($_FILES['files']['tmp_name'][$key]));
        curl_setopt($request, CURLOPT_BUFFERSIZE, 128);
        curl_setopt($request,CURLOPT_POST,true);
        curl_setopt($request, CURLOPT_POSTFIELDS,$image);

        //output the response
        curl_setopt($request,CURLOPT_RETURNTRANSFER,true);
        $status = curl_exec($request);

        //close curl request
        curl_close($request);

        return $status;

    }

}